export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = 'GET_QUESTIONS_FAILURE';

export const REORDER_QUESTIONS = 'REORDER_QUESTIONS';

export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';

export const CHANGE_RATING = 'CHANGE_RATING';
